[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the custom redirects that are causing issues
# The Next.js plugin will handle routing automatically

[dev]
  command = "npm run dev"
  port = 4000
  targetPort = 4000
  framework = "next" 